### ISSUE TITLE
Invalid XML in podcast with `&` in title

### ISSUE THREAD

**Issue by zeyus** [lucasrangit/google-podcasts-export-opml#1]
Thanks for a really useful utility. Not a major issue, but I encountered a problem importing the generated OPML into a podcast app due to invalid XML. The podcast had an ampersand (`&`) in the title, and should be quoted as `&amp;`.

Should be as straightforward as including something like:

```js
function htmlEntities(str) {
    return String(str).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}
```

And changing [line 203 of `scrape.js`](https://github.com/lucasrangit/google-podcasts-export-opml/blob/main/scrape.js#L203) from:

```js
podcast_urls[name] = data.feeds[0].url;
```

to:

```js
podcast_urls[htmlEntities(name)] = data.feeds[0].url;
```

thanks again :) happy to submit it as a PR if you'd prefer.

**Comment by lucasrangit** [comment]
Yes please!
